# Generated by Django 3.0.4 on 2020-10-31 04:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp_url', models.URLField(blank=True, verbose_name='HPのURL')),
                ('twitter_url', models.URLField(blank=True, verbose_name='TwitterのURL')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YoutubeのURL')),
                ('group_name', models.CharField(max_length=50, verbose_name='団体名')),
                ('event_name', models.CharField(max_length=50, verbose_name='イベント名')),
                ('image', models.ImageField(upload_to='images/', verbose_name='画像')),
                ('description', models.CharField(blank=True, max_length=1000, verbose_name='説明')),
                ('r', models.FloatField(default=17.0)),
                ('theta', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'イベント',
                'verbose_name_plural': 'イベント',
            },
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=30, verbose_name='地名')),
                ('image', models.ImageField(upload_to='images/', verbose_name='画像')),
                ('default_direction', models.FloatField(default=0.0, verbose_name='画像の初期方向')),
            ],
            options={
                'verbose_name': 'シーン',
                'verbose_name_plural': 'シーン',
            },
        ),
        migrations.CreateModel(
            name='RelatedScene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene_id', models.IntegerField(default=0, verbose_name='シーンのID')),
                ('direction', models.FloatField(default=0.0, verbose_name='画像の初期方向')),
                ('r', models.FloatField(default=18.0)),
                ('theta', models.FloatField(default=0.0)),
                ('button_size', models.FloatField(default=5.0, verbose_name='ボタンのサイズ')),
                ('parent_scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streetview.Scene')),
            ],
        ),
        migrations.CreateModel(
            name='LiveEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='ライブイベント名')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='開始日時')),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='終了日時')),
                ('image', models.ImageField(upload_to='images/', verbose_name='画像')),
                ('live_url', models.URLField(blank=True, verbose_name='LiveのURL')),
                ('parent_event', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='streetview.Event')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='scene',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='streetview.Scene'),
        ),
    ]
